name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25.0.0'
          elixir-version: '1.13.4'

      - name: Publish to Hex.pm
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: |
          mix deps.get
          mix hex.publish --yes
