name: test
on:
  push:
    paths:
      - .github/workflows/**
      - lib/**
      - test/**
      - mix.exs

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.versions.otp}} / Elixir ${{matrix.versions.elixir}}
    strategy:
      matrix:
        versions:
          - { otp: "25.0.0", elixir: "1.13.4" }
          - { otp: "24.3.4", elixir: "1.13.0" }
          - { otp: "24.3.4", elixir: "1.12.3" }
          - { otp: "24.3.4", elixir: "1.11.4" }
          - { otp: "23.3.4.14", elixir: "1.11.4" }
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.versions.otp}}
          elixir-version: ${{matrix.versions.elixir}}

      - run: mix deps.get
      - run: mix coveralls.github
